version: "3.7"
services:
  database-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=cfabrica46
      - POSTGRES_PASSWORD=01234
      - POSTGRES_DB=api_rest_with_redis_cache
    ports:
      - "5433:5432" 

  database-redis:
    image: redis
    ports:
      - "6378:6379" 

  api:
    build: .
    restart: always
    environment:
      - PORT=8080
      - POSTGRES_HOST=database-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=cfabrica46
      - POSTGRES_PASSWORD=01234
      - POSTGRES_DB=api_rest_with_redis_cache
      - REDIS_URL=database-redis:6379
    depends_on:
      - database-postgres
      - database-redis
    ports:
      - "8080:8080"    





