version: "3.7"
services:
    database-postgres:
        image: postgres
        environment:
            - POSTGRES_USER=cfabrica46
            - POSTGRES_PASSWORD=01234
            - POSTGRES_DB=go_crud
        ports:
            - "5433:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    api:
        build: .
        restart: always
        environment:
            - PORT=7070
            - DB_HOST=database-postgres
            - DB_PORT=5432
            - DB_USERNAME=cfabrica46
            - DB_PASSWORD=01234
            - DB_NAME=go_crud
            - DB_SSLMODE=disable
            - DB_DRIVER=postgres
        depends_on:
            - database-postgres
        ports:
            - "7070:7070"
        # networks:
        #     - bridge

networks:
    default:
        external:
            name: mired
