version: "3.7"
services:
    database-postgres:
        image: postgres
        environment:
            - POSTGRES_USER=cfabrica46
            - POSTGRES_PASSWORD=01234
            - POSTGRES_DB=go_crud
        ports:
            - "5433:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    api:
        build: .
        restart: always
        environment:
            - PORT=8080
            - POSTGRES_HOST=database-postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=cfabrica46
            - POSTGRES_PASSWORD=01234
            - POSTGRES_DB=go_crud
        depends_on:
            - database-postgres
        ports:
            - "8080:8080"
