version: "3.7"
services:
    token:
        image: redis
        ports:
            - "6378:6379"

    api:
        build: .
        restart: always
        environment:
            - PORT=9090
            - REDIS_HOST=token
            - REDIS_PORT=6379
        depends_on:
            - token
        ports:
            - "9090:9090"
