version: "3.7"
services:
    token:
        image: postgres
        environment:
            - POSTGRES_USER=cfabrica46
            - POSTGRES_PASSWORD=01234
            - POSTGRES_DB=go_crud
        ports:
            - "6378:6379"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    api:
        build: .
        restart: always
        environment:
            - PORT=6060
            - POSTGRES_HOST=token
            - POSTGRES_PORT=6379
        depends_on:
            - database-postgres
        ports:
            - "6060:6060"
